# kafka_producer/kafka_producer_service.py
"""
kafka_producer_service.py
Publishes device telemetry to Kafka
Telemetry is generated by ingestion/device_data_generator.py
"""

import json
import time
import os
import logging
from kafka import KafkaProducer, KafkaAdminClient
from kafka.admin import NewTopic
from ingestion.device_data_generator import generate_device_stream

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Get Kafka broker from environment variable
KAFKA_BROKER = os.getenv('KAFKA_BROKER', 'broker:9092')  # Default to broker:9092
RAW_TOPIC = os.getenv("KAFKA_TOPIC_RAW", "raw_h2_data")

# Print configuration at startup
print(f"Configuration:")
print(f"  KAFKA_BROKER env: {os.getenv('KAFKA_BROKER', 'NOT SET')}")
print(f"  Using broker: {KAFKA_BROKER}")
print(f"  Topic: {RAW_TOPIC}")


def validate_settings():
    """
    Validate runtime configuration and fail fast with actionable errors.
    """
    if not KAFKA_BROKER:
        raise ValueError("KAFKA_BROKER is empty")
    if not RAW_TOPIC:
        raise ValueError("KAFKA_TOPIC_RAW is empty")


def create_topic_if_not_exists():
    """
    Create topic if it doesn't exist
    """
    admin_client = None
    try:
        admin_client = KafkaAdminClient(
            bootstrap_servers=[KAFKA_BROKER],
            request_timeout_ms=30000
        )
        
        existing_topics = admin_client.list_topics()
        logger.info(f"Existing topics: {list(existing_topics)}")
        
        if RAW_TOPIC not in existing_topics:
            logger.info(f"Creating topic: {RAW_TOPIC}")
            topic = NewTopic(
                name=RAW_TOPIC,
                num_partitions=3,
                replication_factor=1
            )
            admin_client.create_topics([topic])
            logger.info(f"✅ Topic '{RAW_TOPIC}' created successfully")
        else:
            logger.info(f"✅ Topic '{RAW_TOPIC}' already exists")
            
        return True
        
    except Exception as e:
        logger.warning(f"Could not create topic: {e}")
        return False
    finally:
        if admin_client:
            admin_client.close()

def create_producer(max_retries=15, retry_delay=3):
    """
    Create Kafka producer with retry logic
    """
    
    for attempt in range(max_retries):
        try:
            logger.info(f"Attempting to connect to Kafka at {KAFKA_BROKER} (attempt {attempt + 1}/{max_retries})")
            
            # Try to create topic on first attempt
            if attempt == 0:
                create_topic_if_not_exists()
            
            producer = KafkaProducer(
                bootstrap_servers=[KAFKA_BROKER],
                value_serializer=lambda x: json.dumps(x).encode("utf-8"),
                retries=5,
                request_timeout_ms=30000,
                metadata_max_age_ms=30000,
                max_block_ms=60000
            )
            
            # Wait a bit for metadata
            time.sleep(2)
            
            # Test connection
            partitions = producer.partitions_for(RAW_TOPIC)
            logger.info(f"✅ Connected successfully! Topic '{RAW_TOPIC}' has {len(partitions)} partitions")
            return producer
            
        except Exception as e:
            logger.warning(f"⚠️ Connection error: {e}")
            if attempt < max_retries - 1:
                time.sleep(retry_delay)
            else:
                raise

def main():
    validate_settings()

    # Wait for Kafka to be ready
    logger.info("Waiting 5 seconds for services to initialize...")
    time.sleep(5)
    
    try:
        producer = create_producer()
        message_count = 0
        
        print("\n 🚀 Starting authenticated data stream...")
        print("Press Ctrl+C to stop\n")
        
        while True:
            data = generate_device_stream()
            
            # Send to Kafka
            future = producer.send(
                RAW_TOPIC,
                key=data.get("sensor_id", "unknown").encode(),
                value=data
            )
            
            # Wait for send to complete
            result = future.get(timeout=30)
            message_count += 1
            
            # FIX: Handle missing fields gracefully
            sensor_id = data.get('sensor_id', 'unknown')
            value = data.get('value', 0)
            unit = data.get('unit', 'N/A')
            
            if message_count % 5 == 0:
                logger.info(f"✅ Sent {message_count} messages to Kafka")
            else:
                print(f" [{message_count:03d}] ✅ Sent: {sensor_id} = {value} {unit}")
            
            time.sleep(2)
            
    except KeyboardInterrupt:
        print("\n\n🛑 Stopped by user")
        if 'producer' in locals():
            producer.flush(timeout=10)
            producer.close()
        print(f"📊 Total messages sent: {message_count}")
    except Exception as e:
        logger.error(f"Producer failed: {e}")
        if 'producer' in locals():
            producer.close()
        raise

if __name__ == "__main__":
    main()
