FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY config ./config
COPY domain ./domain
COPY infrastructure ./infrastructure
COPY services ./services
COPY cmd/consumer.py .

COPY TSDB.yml .

ENV PYTHONPATH=/app

CMD ["python", "-u", "consumer.py"]
