FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY config ./config
COPY domain ./domain
COPY infrastructure ./infrastructure
COPY simulator ./simulator
COPY cmd/producer.py .

COPY TSDB.yml .

ENV PYTHONPATH=/app

CMD ["python", "-u", "producer.py"]
