apiVersion: 1

datasources:
  - name: QuestDB
    type: postgres
    url: custom_questdb:8812
    user: ${QUESTDB_USER}
    secureJsonData:
      password: ${QUESTDB_PASSWORD}
    jsonData:
      database: qdb
      sslmode: disable
      timescaledb: false
    editable: false
