apiVersion: 1

datasources:
  - name: QuestDB
    uid: questdb
    type: questdb-questdb-datasource
    jsonData:
      server: custom_questdb
      port: 9000
      tlsSkipVerify: true
    editable: false
