apiVersion: 1

datasources:
  - name: QuestDB
    uid: questdb
    type: postgres
    url: custom_questdb:8812
    user: admin
    secureJsonData:
      password: quest
    jsonData:
      database: qdb
      sslmode: disable
      timescaledb: false
    editable: false
